# Generated by Django 3.1.2 on 2021-12-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_expense_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='income',
            field=models.FloatField(default=0),
        ),
    ]
