# Generated by Django 3.1.2 on 2021-12-05 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211205_0409'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
