# Generated by Django 3.1.2 on 2021-12-07 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='amouunt',
            new_name='amount',
        ),
    ]
